"""add user role field

Revision ID: 8b965a9fabc3
Revises: ddd637a86fa9
Create Date: 2026-01-10 20:23:02.067469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8b965a9fabc3"
down_revision: Union[str, Sequence[str], None] = "ddd637a86fa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type
    userrole_enum = sa.Enum("USER", "ADMIN", "MODERATOR", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users", sa.Column("role", userrole_enum, nullable=False, server_default="USER")
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_column("users", "role")

    # Drop ENUM type
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
